# Generated by Django 3.1.7 on 2021-03-15 14:08

from django.db import migrations, models
import rbac.models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/images/default/default.jpeg', help_text='头像路径', upload_to=rbac.models.user_directory_path, verbose_name='头像路径'),
        ),
    ]
